apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: envoy-gateway
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  ports:
  - name: grpc
    port: 18000
    targetPort: 18000
  selector:
    control-plane: envoy-gateway
