apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certgen
  namespace: envoy-gateway-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: certgen
subjects:
- kind: ServiceAccount
  name: certgen
  namespace: envoy-gateway-system
